server:
  port: "8080"

database:
  host: "db"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "mail_service"

redis:
  host: "redis"
  port: 6379

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"