server:
  port: "8080"

database:
  host: "db"              # Имя контейнера базы данных из docker-compose.yaml
  port: 5432              # Порт PostgreSQL
  user: "postgres"        # Имя пользователя для PostgreSQL
  password: "password"    # Пароль для PostgreSQL
  dbname: "mail_service"  # Имя базы данных

redis:
  host: "redis"           # Имя контейнера Redis из docker-compose.yaml
  port: 6379              # Порт Redis

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"  # URL для RabbitMQ
